// TODO: figure out X/Y => create position
function calculateNextPosition(positions, payout, outcome, timeLeft, price) {
    const sections = []; // TODO: calculate possible sections that are generated by positions
    const newPosition = {
        amount: 0,
        direction: '',
        expectedOutcome: null // For sections
    };

    for (var direction of ['BUY', 'SELL']) {
        for (var amount = 1; amount <= 100; amount++) {
            const expectedOutcome = {};
            const hasBetterOutcome = false; // compare expectedOutcome with newPosition.expectedOutcome
            if (outcome < expectedOutcome && newPosition.expectedOutcome < expectedOutcome) {
                newPosition.amount = amount;
                newPosition.direction = direction;
                newPosition.expectedOutcome = expectedOutcome;
            }
        }
    }

    if (newPosition.expectedOutcome === null) {
        return null;
    }

    return newPosition;
}

function calculateExpectedOutcomeOfSection(positions, section, price, amount, direction) {
}